---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build_api
    image: plugins/downstream
    settings:
      server: 
        from_secret: DRONE_SERVER
      token: 
        from_secret: DRONE_USER_TOKEN
      fork: true
      repositories:
        - andes-k8s/api
        - andes-k8s/app
        - andes-k8s/monitoreo-app
        - andes-k8s/matriculaciones

  - name: build_image
    image: plugins/docker   
    settings:
      debug: true
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      registry: new-docker-registry.192-168-0-8.nip.io:30443
      repo: new-docker-registry.192-168-0-8.nip.io:30443/andesnqn/nginx
      context: docker
      dockerfile: docker/andes.Dockerfile
      tags: ["${DRONE_BRANCH}", "${DRONE_BRANCH}-${DRONE_COMMIT_SHA}"]
      build_args:
        - APP=${APP_BRANCH}
        - MATRICULACIONES=${MATRICULACIONES_BRANCH}
      insecure: true

  - name: start_container
    image: orlandobrea/andes-dind:latest
    commands:
      - cd docker
      - API=${API_BRANCH} APP=${APP_BRANCH} docker-compose -f docker-compose.yml down -v
      - API=${API_BRANCH} APP=${APP_BRANCH} docker-compose -f docker-compose.yml up -d



# PARAMS:
#   - APP_BRANCH
#   - API_BRANCH
#   - MATRICULACIONES_BRANCH
#   - MONITOREO_BRANCH
#   - TEST_BRANCH
#   - CRYPRESS_PARAMS